### PR TITLE
Create Blog Post: Slate

### PR DESCRIPTION
**Pull request by asimonson1125**
image incoming.
Looks like something might have changed in relation to the image file path and the 'assets/images/' portion might not be needed.  Leaving that to whoever gets the image uploaded

### CODE REVIEW

**Review by Mstrodl — APPROVED** [review]
:shipit:

**Review by WillNilges — APPROVED** [review]
Nice

**Review by Mstrodl — CHANGES_REQUESTED** [review]
Can you include the image in your PR?

**Comment by Mstrodl** [comment]
Can you squash these and rebase against master?

**Comment by Mstrodl** [comment]
wait I have technology

**Review by Mstrodl — APPROVED** [review]

**Pull request merged**
