### PR TITLE
Add EventLCD to Projects Page

### PR DESCRIPTION
**Pull request by liam-middlebrook**
This could probably use a new image, but it's a tricky situation. It's nice to
get an image when it's slightly darker so the LCD text shows up clearer, but
then the background fades and is overwhelmed by the radiance of the screen.

### CODE REVIEW

**Comment by mbillow** [comment]
Definitely needs a new picture, but I think this is a cool thing to have on the projects page.

**Comment by brandonhudson** [comment]
Any updates on this - I think we're waiting on a new photo right?

**Comment by liam-middlebrook** [comment]
Yeah, I've been trying to get a higher quality photo, but with general lighting on floor it's kind of tough.

**Comment by liam-middlebrook** [comment]
Updated the picture, I spliced two photos with different focus points together. If someone wants the sources and think they can do better, feel free to go ahead.

**Comment by liam-middlebrook** [comment]
Well, the lounge eventlcd is missing! So unless it magically appears what's in the commit is the final image that will come up for quite a while.

**Comment by liam-middlebrook** [comment]
ping?

**Pull request merged**
