### PR TITLE
Update rooms included on tour page

### PR DESCRIPTION
**Pull request by rswiernik**
🤷

### CODE REVIEW

**Review by Dr-N0 — APPROVED** [review]
👍

**Review by zthart — APPROVED** [review]
What's up gamers can I get a like and subscribe please smash that mf merge button let's gooooooo 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚢 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Comment by RamZallan** [comment]
lgtm

**Comment by RamZallan** [comment]
Wait @rswiernik, you have to remove the entries here too I think https://www.github.com/ComputerScienceHouse/CSHPublicSite/tree/develop/assets%2Fjs%2Ftour.js

**Comment by rswiernik** [comment]
Word, let me add that.

Also, a note - i'm having issues running Jekyll on my laptop ([likely due to issues with things not playing nice on Big Sur](https://ernestojeh.com/fix-jekyll-on-macos-big-sur)) so I can't test this at the moment. I can test this later once I'm on a different machine, but if ya'll want this merged faster I would love a hand testing this.

**Comment by rswiernik** [comment]
Finally decided to close all the tabs that I had open on my laptop and came across this PR which I had forgotten about. Long story short, popped everything into a docker container to test and things look fine from what I can see. I've included a screenshot of what the tour dropdown looks like now:

Screen Shot 2021-08-03 at 9 40 42 AM

I'll let one of you guys merge this since I have no idea how ya'll do things now adays.

**Pull request merged**
