### PR TITLE
Pubsite Rewrite 2019 -- Jekyll this time!

### LINKED ISSUE #168: Add FAQ Page
We're facing more and more public criticism / skepticism about the processes and activities that we go through during the introductory process for incoming freshman students. To combat this, I propose that we become much more transparent about every step of the process, and break down what differentiates us from stereotypical fraternal organizations. With this, I'm hoping that we can better inform incoming students and parents about what exactly CSH is and what the process looks like for applying.

Initial topic ideas:

- Is CSH a Frat?
- What is the introductory process like?
- What is Freshman Project?
- What happens if I’m not accepted?

Please comment with thoughts / concerns - I'm going to leave this open for a couple weeks so we can have discussion.

### LINKED ISSUE #178: Update Photos/Show More Photos
As cool as it is having a lot of older CSH photos on the site, a lot of the photos are a bit dated to what CSH looks like today.
[Traditions](https://www.csh.rit.edu/traditions.html) Is a good example of this. We could benefit from a little bit of an update in this area.

We could also benefit I believe from adding the hoverover [found on the EBoard page](https://www.csh.rit.edu/eboard.html) to other sections of the site from [Traditions](https://www.csh.rit.edu/traditions.html) to [projects](https://www.csh.rit.edu/projects.html) to show off a little bit more of what makes CSH Great.

### LINKED ISSUE #179: Independent "How to Apply" Page
Right now when you select "How to Apply" from the bottom sitemap, it bring you to [Membership](https://www.csh.rit.edu/membership.html) which includes the few lines:

-----------------------

#### Incoming Students
After being accepted to RIT, look for the Special Interest Housing selection in your RIT housing application to apply to CSH.

#### Current Students
Students already enrolled at RIT can apply to join CSH at any time. The best way to apply is to visit CSH (on the third floor of Nathaniel Rochester Hall) and pick up an application from our Evaluations Director. All majors and years are accepted and members can live on or off floor.

-----------------------

We should have a page dedicated to applying to CSH, what's involved, and outlining the Application/Intro process.

### LINKED ISSUE #198: Contact form broken
The contact form currently errors with every message you try to send.

Error stack trace:
```
PHP Warning:  require(key.php): failed to open stream: No such file or directory in /var/www/pub/public-site/resources/php/mailer.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/pub/public-site/resources/php/mailer.php:0
PHP Fatal error:  require(): Failed opening required 'key.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/pub/public-site/resources/php/mailer.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/pub/public-site/resources/php/mailer.php:0
```

### PR DESCRIPTION
**Pull request by RamZallan**
🎉 🚢 :shipit: 🚀

View it live at [pubsite.a.csh.rit.edu](pubsite.a.csh.rit.edu)!

Here's a few previews, as well:
image

image

Closes #168
Closes #178
Closes #179
Closes #198

### CODE REVIEW

**Comment by rswiernik** [comment]
You might have already thought about this but since this PR is `G R A N D E`, it's probably worth squashing out commits so this is a nice clean cut over that can be easily tagged.

**Comment by RamZallan** [comment]
@rswiernik would it make sense to just Squash + Merge? There's a few merge commits in the PR and some history was lost anyways moving between repos (originally on CSHPublicSiteV2, then my fork of this repo).

**Comment by rswiernik** [comment]
I'm not sure that preserving the history for the dev of new versions of the site is really that important. If _really_ wanted to, you could merge it into a separate historical branch on this repo, then merge that branch to master, squash the master history, then force push the new master history?

eg:
```
... Do some shit to get the history set up ...
[Reeds-MBP] tmp ❯ git checkout history                               (master|✔)
Switched to branch 'history'
[Reeds-MBP] tmp ❯ tree                                              (history|✔)
.
├── a
├── asdf
├── that
└── this

0 directories, 4 files
[Reeds-MBP] tmp ❯ git checkout master                                                                                         (history|✔)
Switched to branch 'master'
[Reeds-MBP] tmp ❯ git merge --squash history                                                                                   (master|✔)
Updating 72cf0f4..8dff9e0
Fast-forward
Squash commit -- not updating HEAD
 a    | 0
 asdf | 0
 that | 0
 3 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a
 create mode 100644 asdf
 create mode 100644 that
[Reeds-MBP] tmp ❯ git log                                                                                                     (master|●3)
commit 72cf0f454d727369384043c5073146c6a8b7651d (HEAD -> master)
Author: Reed Swiernik <reed@plum.wine>
Date:   Wed Aug 7 15:36:33 2019 -0700

    first
[Reeds-MBP] tmp ❯ git status                                                                                                  (master|●3)
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   a
	new file:   asdf
	new file:   that

[Reeds-MBP] tmp ❯ git commit -a -m "Update to new version"                                                                    (master|●3)
[master a898d3e] Update to new version
 3 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a
 create mode 100644 asdf
 create mode 100644 that

**Comment by rswiernik** [comment]
All that said, I would definitely prioritize having a single clean commit on master. But that's just me.

**Comment by rswiernik** [comment]
Also, obligatory mention, this is your time to sneakily change the organization colors back to green/white/black. Just making sure that you have all the information you need before you merge this ;)

**Comment by RamZallan** [comment]
Fixes #168 #178 #179 #198

**Pull request merged**
