### PR TITLE
Nitpicks on 'about' page wording

### PR DESCRIPTION
**Pull request by Mstrodl**
Hopefully these should make this page easier to understand...

### CODE REVIEW

**Review by mxmeinhold — APPROVED** [review]

**Comment by mxmeinhold** [comment]
Wait why is this based against master?

**Comment by mxmeinhold** [comment]
You probably should rebase now that I've changed the PR target.

**Comment by Mstrodl** [comment]
@mxmeinhold my understanding was that `develop` wasn't deployed anywhere and this was more of a hotfix so :woman_shrugging:

**Comment by devinmatte** [comment]
@Mstrodl It's deployed to wwwtest.csh.rit.edu

**Review by adamhb123 — APPROVED** [review]
👴

**Pull request merged**
