### PR TITLE
Alumni Employers

### PR DESCRIPTION
**Pull request by brandonhudson**
Added Über, Oculus, and Harvard to alumni employers

### CODE REVIEW

**Comment by rswiernik** [comment]
The Uber logo looks like it has white inside the B and the R, can you double check that they are correct?

**Comment by brandonhudson** [comment]
Good catch. My eye couldn't even see that when I was working on it.

**Comment by stevenmirabito** [comment]
The Oculus logo has the same issue in the "O".

**Comment by brandonhudson** [comment]
No, its correct. It's background is an alpha channel.

**Comment by brandonhudson** [comment]
Sorry, checked the wrong logo. I had a copy of the old one with the eye.

**Comment by stevenmirabito** [comment]
:thumbsup:

**Pull request merged**
